apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  namespace: default
  labels:
   name: result-app-deployment
   app: demo-voting-app
spec:
  selector:
    matchLabels:
      app: result-app
  replicas: 1
  template:
   metadata:
      name: result-app
      labels: 
        app: result-app
   spec:
    containers:
     - name: result-app
       image: kodekloud/examplevotingapp_result:v1
       ports:
        - containerPort: 80
       resources:
        limits:
         memory: 256Mi
         cpu: "0.5"
        requests:
         memory: 128Mi
         cpu: "0.2"