apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: default
  labels:
   name: postgres-deployment
   app: demo-voting-app
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
   metadata:
      name: postgres
      labels: 
        app: postgres
   spec:
    containers:
     - name: postgres
       image: postgres:9.4
       ports:
        - containerPort: 5432
       env: 
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust 
       resources:
        limits:
         memory: 256Mi
         cpu: "0.5"
        requests:
         memory: 128Mi
         cpu: "0.2"