apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: default
  labels:
   name: redis-deployment
   app: demo-voting-app
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
   metadata:
      name: redis
      labels: 
        app: redis
   spec:
    containers:
     - name: redis
       image: redis
       ports:
        - containerPort: 6379
       resources:
        limits:
         memory: 256Mi
         cpu: "0.5"
        requests:
         memory: 128Mi
         cpu: "0.2"